global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'propsdb'
    static_configs:
      - targets: ['propsdb:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
