basePath: /api
host: localhost:3000
info:
  contact:
    email: info@localnerve.com
    name: API Support
    url: https://github.com/localnerve/propsdb
  description: Go Fiber data service with multi-database support
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
  termsOfService: http://swagger.io/terms/
  title: PropsDB API
  version: 1.0.0
paths: {}
schemes:
- http
- https
securityDefinitions:
  CookieAuth:
    in: cookie
    name: cookie_session
    type: apiKey
swagger: "2.0"
