name: Verify
on:
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '24.12.0'
  GO_VERSION: '1.25.5'

jobs:
  verify:
    runs-on: ubuntu-24.04
    name: 'Verify Jam-Build-PropsDB'
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Setup Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # 6.2.0
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Setup Node deps
      run: |
        npm ci
        npx playwright install --with-deps
    - name: Setup Go deps
      run: make deps
    - name: Run Go Checks
      run: make check
    - name: Run Playwright E2E # This builds the cover test image
      run: make test-e2e-js-cover
    - name: Run Go Unit
      run: make test-unit
    - name: Run Go Integration
      run: make test-integration
    - name: Run Go E2E
      run: make test-e2e